[project]
name = "depcheck"
version = "0.1.0"
description = "Dependency checker for known vulnerabilities for python - SBOM from cyclonedx - vulnerabilities from grype."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cyclonedx-py>=1.0.1",
]
license = { text = "Apache-2.0" }
